### ISSUE TITLE
Bug sonore

### ISSUE THREAD

**Issue by RikHart90** [Guilouz/BTT-TFT43-CR-10S-PRO#1]
Bonsoir,

 j ai un bug quand je veux enlever les notifications sonore sur l écran,  en effet sa ne fonctionne pas en le désactivant, merci beaucoup pour tout votre travail Mr ^^ 

Cordialement,

**Comment by Guilouz** [comment]
Je viens de tester à l'instant, aucun problème de mon côté. Assure toi de réinitialiser les paramètres de l'écran après installation de la dernière mise à jour.

Sur l'écran naviguez dans Menu - Options - Paramètres puis accédez à la dernière page. Cliquez ensuite sur RàZ des paramètres.

**Comment by RikHart90** [comment]
Super, merci beaucoup ^^
j ai d'autre petit soucis mais rien de méchant:
notification a chaque print : unknown command: "" (j ai regarder dans le gcode cura mais je n ai rien trouver)
commande extrudeur décharger fonctionne nickel mais charger le filament ne s’arrête pas

**Comment by Guilouz** [comment]
Quelle est la commande ? Sans la commande je ne peux pas faire grand chose ^^

Je l'utilise beaucoup la fonction charger/décharger avec mon DDX, aucun soucis de mon côté. Installe la dernière maj et fais un reset.

**Comment by RikHart90** [comment]
malheureusement il n'y a pas de commande afficher juste les 2 guillemets, cela s'affiche exactement comme ça : 
unknown command: ""

mais comme sa ne fais aucune incidence sur mon print, du coup, pas grave ^^
Merci beaucoup pour votre réactivité :)

**Comment by RikHart90** [comment]
Problème de la notification unknown command: "" résolue juste en faisant la mise a jour de marlin ^^ 

Merci beaucoup pour les mise a jour tft  :)
